config/routes.rb
Rails.application.routes.draw do

  
  resources :species
  root "species#index"
end

app/models/species.rb
class Species < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  
  def index
    @species = Species.all.order('created_at DESC')
  end
  
  def new
    @species = Species.new
  end
  
  def create
    @species = Species.new(species_params)
    
    if @species.save
      redirect_to @species
    else
      render 'new'
    end 
  end
  
  def show
    @species = Species.find(params[:id])
  end
  
  def update
    @species = Species.find(params[:id])
    
    if @species.update(species_params)
      redirect_to @species
    else
      render 'edit'
    end
  end
  
  def edit
    @species = Species.find(params[:id])
  end
  
  def destroy
    @species = Species.find(params[:id])
    @species.destroy
    
    redirect_to @species
  end
  
  private
  
  def species_params
    params.require(:species).permit(:latinName, :commonName, :description)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body>
<section class="hero is-primary">
  <div class='hero-head'>
  <div class='navbar'>
    <div class='container'>
      <div class='navbar-brand'>
        <%= link_to 'BiologyApp_RubyRails', root_path, class: 'navbar-item' %>
        <span class='navbar-burger burger' data-target='navbarNenuHeroA'>
          <span></span>
          <span></span>
          <span></span>
        </span>
      </div>
      <div id='navbarMenuHeroA' class='navbar-menu'>
        <div class='navbar-end'>
          <%= link_to 'Add New Species', new_species_path, class:'navbar-item' %>
        </div>
      </div>
    </div>
  </div>
  </div>

  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= yield :page_title %>
      </h1>
    </div>
  </div>
</section>


<%= yield %>

</body>
</html>

app/views/species/_form.html.erb
<div class='section'>
<%= simple_form_for @species do |f| %>
  <div class='field'>
    <div class='control'>
      <%= f.input :latinName, input_html: { class: 'input' }, wrapper: false, label: 'Latin Name' %>
    </div>
  </div>
  
  <div class='field'>
    <div class='control'>
      <%= f.input :commonName, input_html: { class: 'input' }, wrapper: false, label: 'Common Name' %>
    </div>
  </div>

<div class='field'>
  <div class='control'>
    <%= f.input :description, input_html: { class: 'textarea' }, wrapper: false, label: 'Description' %>
  </div>
</div>

<%= f.button :submit, class: 'button is-primary' %>

<% end %>
</div>

app/views/species/edit.html.erb
<% content_for :page_title, "Edit post" %>

<%= render 'form' %>

app/views/species/index.html.erb
<% content_for :page_title, 'My Species' %>

<section class='section'>
  <div class='container'>
    <% @species.each do |species| %>
      <div class='card'>
        <div class='card-content'>
          <div class='media'>
            <div class='media-content'>
              <div class='is-italic'>
                <p class='title is-4'> 
                  <%= link_to species.latinName, species %> </p>
              </div>
            <p class='title is-6'> <%= species.commonName %> </p>
            </div>
          </div>
          <div class='content'>
            <%= species.description %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/species/new.html.erb
<% content_for :page_title, 'Add New Species' %>

<%= render 'form' %>

app/views/species/show.html.erb
<section class='section'>
  <div class='container'>
    <nav class='level'>
      <!-- Left side -->
      <div class='level-left'>
        <div class='is-italic'>
          <h1 class='title'>
            <%= @species.latinName %>
          </h1>
        </div>
      </div>
      
      <!-- Right Side -->
      <div class='level-right'>
        <p class='level-item'>
          <%= link_to 'Edit', edit_species_path(@species), class: 'button' %>
        </p>
        <p class='level-item'>
          <%= link_to 'Delete', species_path(@species), method: :delete, data: { confirm: "Are you sure?" }, class: "button is-danger" %>
        </p>
      </div>
    </nav>
    <hr />
    
    
    <h1 class='subtitle'>
      <%= @species.commonName %>
    </h1>
    <div class='content'>
      <%= @species.description %>
    </div>
  </div>
</section>